-- Phase 1 user registry and ownership migration.
-- Compatible with either the original shared-list schema (no user_id) or
-- the interim text user_id schema. All existing lists and catalogue rows stay.
-- Run atomically: drizzle-kit migrate, or psql -v ON_ERROR_STOP=1 -1 -f <file>

CREATE TABLE IF NOT EXISTS "users" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "email" text,
  "auth_subject" text,
  "development_key" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "users_email_unique" UNIQUE("email"),
  CONSTRAINT "users_auth_subject_unique" UNIQUE("auth_subject"),
  CONSTRAINT "users_development_key_unique" UNIQUE("development_key")
);
--> statement-breakpoint
-- A/B are deliberately passwordless *test labels*, not authentication.
-- The legacy account is not resolvable by the development user selector.
INSERT INTO "users" ("development_key")
VALUES ('dev-user-a'), ('dev-user-b'), ('legacy-unclaimed')
ON CONFLICT ("development_key") DO NOTHING;
--> statement-breakpoint
DO $$
BEGIN
  -- Interim deployments: retain the old string IDs instead of casting them.
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema() AND table_name = 'shopping_lists'
      AND column_name = 'user_id' AND data_type = 'text'
  ) THEN
    ALTER TABLE "shopping_lists" RENAME COLUMN "user_id" TO "legacy_user_id";
  END IF;

  -- Original deployments had no user_id at all; those rows are unclaimed.
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema() AND table_name = 'shopping_lists'
      AND column_name = 'legacy_user_id'
  ) THEN
    ALTER TABLE "shopping_lists" ADD COLUMN "legacy_user_id" text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema() AND table_name = 'shopping_lists'
      AND column_name = 'user_id'
  ) THEN
    ALTER TABLE "shopping_lists" ADD COLUMN "user_id" integer;
  END IF;
END $$;
--> statement-breakpoint
ALTER TABLE "shopping_lists" ALTER COLUMN "legacy_user_id" DROP NOT NULL;
--> statement-breakpoint
-- Preserve every interim label, including unexpected ones, without exposing
-- them through the allowlisted A/B development selector.
INSERT INTO "users" ("development_key")
SELECT DISTINCT "legacy_user_id" FROM "shopping_lists"
WHERE "legacy_user_id" IS NOT NULL AND trim("legacy_user_id") <> ''
ON CONFLICT ("development_key") DO NOTHING;
--> statement-breakpoint
UPDATE "shopping_lists" AS list
SET "user_id" = owner."id"
FROM "users" AS owner
WHERE list."user_id" IS NULL AND list."legacy_user_id" = owner."development_key";
--> statement-breakpoint
-- Original shared rows have no known owner. Quarantine, don't guess an owner.
UPDATE "shopping_lists"
SET "user_id" = (SELECT "id" FROM "users" WHERE "development_key" = 'legacy-unclaimed')
WHERE "user_id" IS NULL;
--> statement-breakpoint
-- Keep an interim user's active draft under their new numeric ID. Original
-- 'current' stays quarantined, and a conflicting new ID is never overwritten.
UPDATE "shopping_lists" AS list
SET "id" = 'current_' || list."user_id"::text
WHERE list."legacy_user_id" IS NOT NULL
  AND list."id" = 'current_' || list."legacy_user_id"
  AND NOT EXISTS (
    SELECT 1 FROM "shopping_lists" AS other
    WHERE other."id" = 'current_' || list."user_id"::text
  );
--> statement-breakpoint
ALTER TABLE "shopping_lists" ALTER COLUMN "user_id" SET NOT NULL;
--> statement-breakpoint
-- The interim index followed the renamed text column; rebuild on integer ID.
DROP INDEX IF EXISTS "shopping_lists_user_id_idx";
--> statement-breakpoint
CREATE INDEX "shopping_lists_user_id_idx" ON "shopping_lists" ("user_id");
--> statement-breakpoint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'shopping_lists_user_id_users_id_fk'
      AND conrelid = 'shopping_lists'::regclass
  ) THEN
    ALTER TABLE "shopping_lists" ADD CONSTRAINT "shopping_lists_user_id_users_id_fk"
      FOREIGN KEY ("user_id") REFERENCES "users"("id");
  END IF;
END $$;
