-- Run this migration as a single transaction on existing installations:
-- psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -1 -f drizzle/0002_equal_starhawk.sql
-- Back up first. Existing categories/products are retained as a read-only archive.
CREATE TABLE "user_categories" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "name" text NOT NULL,
  "icon" text DEFAULT 'grid' NOT NULL,
  "tint" text DEFAULT '#EDEFF2' NOT NULL,
  "sort_order" integer DEFAULT 0 NOT NULL,
  CONSTRAINT "user_categories_id_user_id_unique" UNIQUE ("id", "user_id")
);
--> statement-breakpoint
CREATE TABLE "user_products" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "category_id" integer NOT NULL,
  "name" text NOT NULL,
  "quantity" integer DEFAULT 1 NOT NULL,
  "unit" text DEFAULT 'kg' NOT NULL,
  "sort_order" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "catalog_initialized" boolean DEFAULT false NOT NULL;
--> statement-breakpoint
ALTER TABLE "user_categories" ADD CONSTRAINT "user_categories_user_id_users_id_fk"
  FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE cascade;
--> statement-breakpoint
ALTER TABLE "user_products" ADD CONSTRAINT "user_products_user_id_users_id_fk"
  FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE cascade;
--> statement-breakpoint
ALTER TABLE "user_products" ADD CONSTRAINT "user_products_category_owner_fk"
  FOREIGN KEY ("category_id", "user_id") REFERENCES "user_categories"("id", "user_id") ON DELETE cascade;
--> statement-breakpoint
CREATE INDEX "user_categories_user_id_idx" ON "user_categories" ("user_id");
--> statement-breakpoint
CREATE INDEX "user_products_user_category_idx" ON "user_products" ("user_id", "category_id");
--> statement-breakpoint
-- Generate unique private IDs, retaining an exact old->new mapping for each
-- owner. In particular, IDs within shopping_lists.items cannot be left pointing
-- at the old shared product table.
CREATE TEMP TABLE _category_id_map (
  owner_id integer NOT NULL,
  old_id integer NOT NULL,
  new_id integer NOT NULL,
  PRIMARY KEY (owner_id, old_id)
);
--> statement-breakpoint
INSERT INTO _category_id_map (owner_id, old_id, new_id)
SELECT u.id, c.id, nextval(pg_get_serial_sequence('user_categories', 'id'))::integer
FROM "users" u CROSS JOIN "categories" c;
--> statement-breakpoint
INSERT INTO "user_categories" ("id", "user_id", "name", "icon", "tint", "sort_order")
SELECT m.new_id, m.owner_id, c.name, c.icon, c.tint, c.sort_order
FROM _category_id_map m JOIN "categories" c ON c.id = m.old_id;
--> statement-breakpoint
CREATE TEMP TABLE _product_id_map (
  owner_id integer NOT NULL,
  old_id integer NOT NULL,
  new_id integer NOT NULL,
  new_category_id integer NOT NULL,
  PRIMARY KEY (owner_id, old_id)
);
--> statement-breakpoint
INSERT INTO _product_id_map (owner_id, old_id, new_id, new_category_id)
SELECT m.owner_id, p.id, nextval(pg_get_serial_sequence('user_products', 'id'))::integer, m.new_id
FROM "products" p JOIN _category_id_map m ON m.old_id = p.category_id;
--> statement-breakpoint
INSERT INTO "user_products" ("id", "user_id", "category_id", "name", "quantity", "unit", "sort_order")
SELECT m.new_id, m.owner_id, m.new_category_id, p.name, p.quantity, p.unit, p.sort_order
FROM _product_id_map m JOIN "products" p ON p.id = m.old_id;
--> statement-breakpoint
-- Remap active and saved snapshots in place, keeping quantities, names, notes,
-- order, timestamps and item_count unchanged. For an already-deleted legacy
-- product, preserve its old IDs in extra audit fields but replace its selectable
-- ID with a negative per-list tombstone. Otherwise that old ID could collide
-- with an unrelated newly generated private product ID.
UPDATE "shopping_lists" AS list
SET "items" = COALESCE((
  SELECT jsonb_agg(
    CASE
      WHEN mapped.new_id IS NOT NULL THEN jsonb_set(
        jsonb_set(entry.item, '{productId}', to_jsonb(mapped.new_id)),
        '{categoryId}', to_jsonb(mapped.new_category_id)
      )
      WHEN jsonb_typeof(entry.item) = 'object' AND entry.item ? 'productId' THEN
        entry.item || jsonb_build_object(
          'legacyProductId', entry.item->'productId',
          'legacyCategoryId', entry.item->'categoryId',
          'productId', -entry.position::integer,
          'categoryId', -entry.position::integer
        )
      ELSE entry.item
    END ORDER BY entry.position
  )
  FROM jsonb_array_elements(list.items) WITH ORDINALITY AS entry(item, position)
  LEFT JOIN _product_id_map mapped
    ON mapped.owner_id = list.user_id
    AND mapped.old_id::text = entry.item->>'productId'
), '[]'::jsonb)
WHERE jsonb_typeof(list.items) = 'array';
--> statement-breakpoint
-- The durable flag prevents deleted-empty catalogues from being reseeded later.
-- If the legacy catalogue was empty, leave the flag false so new requests
-- initialize from the immutable SEED_CATALOG source instead.
UPDATE "users" SET "catalog_initialized" = true
WHERE EXISTS (SELECT 1 FROM "categories");
--> statement-breakpoint
DROP TABLE _product_id_map;
--> statement-breakpoint
DROP TABLE _category_id_map;
